// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.30.2

package com.sirius.bootstrap.msg;

public final class Msg {
  private Msg() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Msg.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sirius.bootstrap.msg.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
     * @return Whether the moveMessage field is set.
     */
    boolean hasMoveMessage();
    /**
     * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
     * @return The moveMessage.
     */
    MoveMessage getMoveMessage();
    /**
     * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
     */
    MoveMessageOrBuilder getMoveMessageOrBuilder();

    Message.MsgIdCase getMsgIdCase();
  }
  /**
   * Protobuf type {@code com.sirius.bootstrap.msg.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.sirius.bootstrap.msg.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_com_sirius_bootstrap_msg_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_com_sirius_bootstrap_msg_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    private int msgIdCase_ = 0;
    @SuppressWarnings("serial")
    private Object msgId_;
    public enum MsgIdCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      MOVEMESSAGE(1001),
      MSGID_NOT_SET(0);
      private final int value;
      private MsgIdCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgIdCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgIdCase forNumber(int value) {
        switch (value) {
          case 1001: return MOVEMESSAGE;
          case 0: return MSGID_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgIdCase
    getMsgIdCase() {
      return MsgIdCase.forNumber(
          msgIdCase_);
    }

    public static final int MOVEMESSAGE_FIELD_NUMBER = 1001;
    /**
     * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
     * @return Whether the moveMessage field is set.
     */
    @Override
    public boolean hasMoveMessage() {
      return msgIdCase_ == 1001;
    }
    /**
     * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
     * @return The moveMessage.
     */
    @Override
    public MoveMessage getMoveMessage() {
      if (msgIdCase_ == 1001) {
         return (MoveMessage) msgId_;
      }
      return MoveMessage.getDefaultInstance();
    }
    /**
     * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
     */
    @Override
    public MoveMessageOrBuilder getMoveMessageOrBuilder() {
      if (msgIdCase_ == 1001) {
         return (MoveMessage) msgId_;
      }
      return MoveMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgIdCase_ == 1001) {
        output.writeMessage(1001, (MoveMessage) msgId_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgIdCase_ == 1001) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1001, (MoveMessage) msgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      if (!getMsgIdCase().equals(other.getMsgIdCase())) return false;
      switch (msgIdCase_) {
        case 1001:
          if (!getMoveMessage()
              .equals(other.getMoveMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgIdCase_) {
        case 1001:
          hash = (37 * hash) + MOVEMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getMoveMessage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sirius.bootstrap.msg.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sirius.bootstrap.msg.Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_com_sirius_bootstrap_msg_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_com_sirius_bootstrap_msg_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using com.sirius.bootstrap.msg.Msg.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (moveMessageBuilder_ != null) {
          moveMessageBuilder_.clear();
        }
        msgIdCase_ = 0;
        msgId_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_com_sirius_bootstrap_msg_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(Message result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(Message result) {
        result.msgIdCase_ = msgIdCase_;
        result.msgId_ = this.msgId_;
        if (msgIdCase_ == 1001 &&
            moveMessageBuilder_ != null) {
          result.msgId_ = moveMessageBuilder_.build();
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        switch (other.getMsgIdCase()) {
          case MOVEMESSAGE: {
            mergeMoveMessage(other.getMoveMessage());
            break;
          }
          case MSGID_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8010: {
                input.readMessage(
                    internalGetMoveMessageFieldBuilder().getBuilder(),
                    extensionRegistry);
                msgIdCase_ = 1001;
                break;
              } // case 8010
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int msgIdCase_ = 0;
      private Object msgId_;
      public MsgIdCase
          getMsgIdCase() {
        return MsgIdCase.forNumber(
            msgIdCase_);
      }

      public Builder clearMsgId() {
        msgIdCase_ = 0;
        msgId_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          MoveMessage, MoveMessage.Builder, MoveMessageOrBuilder> moveMessageBuilder_;
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       * @return Whether the moveMessage field is set.
       */
      @Override
      public boolean hasMoveMessage() {
        return msgIdCase_ == 1001;
      }
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       * @return The moveMessage.
       */
      @Override
      public MoveMessage getMoveMessage() {
        if (moveMessageBuilder_ == null) {
          if (msgIdCase_ == 1001) {
            return (MoveMessage) msgId_;
          }
          return MoveMessage.getDefaultInstance();
        } else {
          if (msgIdCase_ == 1001) {
            return moveMessageBuilder_.getMessage();
          }
          return MoveMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       */
      public Builder setMoveMessage(MoveMessage value) {
        if (moveMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgId_ = value;
          onChanged();
        } else {
          moveMessageBuilder_.setMessage(value);
        }
        msgIdCase_ = 1001;
        return this;
      }
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       */
      public Builder setMoveMessage(
          MoveMessage.Builder builderForValue) {
        if (moveMessageBuilder_ == null) {
          msgId_ = builderForValue.build();
          onChanged();
        } else {
          moveMessageBuilder_.setMessage(builderForValue.build());
        }
        msgIdCase_ = 1001;
        return this;
      }
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       */
      public Builder mergeMoveMessage(MoveMessage value) {
        if (moveMessageBuilder_ == null) {
          if (msgIdCase_ == 1001 &&
              msgId_ != MoveMessage.getDefaultInstance()) {
            msgId_ = MoveMessage.newBuilder((MoveMessage) msgId_)
                .mergeFrom(value).buildPartial();
          } else {
            msgId_ = value;
          }
          onChanged();
        } else {
          if (msgIdCase_ == 1001) {
            moveMessageBuilder_.mergeFrom(value);
          } else {
            moveMessageBuilder_.setMessage(value);
          }
        }
        msgIdCase_ = 1001;
        return this;
      }
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       */
      public Builder clearMoveMessage() {
        if (moveMessageBuilder_ == null) {
          if (msgIdCase_ == 1001) {
            msgIdCase_ = 0;
            msgId_ = null;
            onChanged();
          }
        } else {
          if (msgIdCase_ == 1001) {
            msgIdCase_ = 0;
            msgId_ = null;
          }
          moveMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       */
      public MoveMessage.Builder getMoveMessageBuilder() {
        return internalGetMoveMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       */
      @Override
      public MoveMessageOrBuilder getMoveMessageOrBuilder() {
        if ((msgIdCase_ == 1001) && (moveMessageBuilder_ != null)) {
          return moveMessageBuilder_.getMessageOrBuilder();
        } else {
          if (msgIdCase_ == 1001) {
            return (MoveMessage) msgId_;
          }
          return MoveMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.com.sirius.bootstrap.msg.MoveMessage moveMessage = 1001;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          MoveMessage, MoveMessage.Builder, MoveMessageOrBuilder>
          internalGetMoveMessageFieldBuilder() {
        if (moveMessageBuilder_ == null) {
          if (!(msgIdCase_ == 1001)) {
            msgId_ = MoveMessage.getDefaultInstance();
          }
          moveMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              MoveMessage, MoveMessage.Builder, MoveMessageOrBuilder>(
                  (MoveMessage) msgId_,
                  getParentForChildren(),
                  isClean());
          msgId_ = null;
        }
        msgIdCase_ = 1001;
        onChanged();
        return moveMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.sirius.bootstrap.msg.Message)
    }

    // @@protoc_insertion_point(class_scope:com.sirius.bootstrap.msg.Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MoveMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sirius.bootstrap.msg.MoveMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string playerId = 1;</code>
     * @return The playerId.
     */
    String getPlayerId();
    /**
     * <code>string playerId = 1;</code>
     * @return The bytes for playerId.
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    /**
     * <code>float posX = 2;</code>
     * @return The posX.
     */
    float getPosX();

    /**
     * <code>float posY = 3;</code>
     * @return The posY.
     */
    float getPosY();

    /**
     * <code>float posZ = 4;</code>
     * @return The posZ.
     */
    float getPosZ();

    /**
     * <code>float rotX = 5;</code>
     * @return The rotX.
     */
    float getRotX();

    /**
     * <code>float rotY = 6;</code>
     * @return The rotY.
     */
    float getRotY();

    /**
     * <code>float rotZ = 7;</code>
     * @return The rotZ.
     */
    float getRotZ();
  }
  /**
   * Protobuf type {@code com.sirius.bootstrap.msg.MoveMessage}
   */
  public static final class MoveMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.sirius.bootstrap.msg.MoveMessage)
      MoveMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        MoveMessage.class.getName());
    }
    // Use MoveMessage.newBuilder() to construct.
    private MoveMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MoveMessage() {
      playerId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_com_sirius_bootstrap_msg_MoveMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_com_sirius_bootstrap_msg_MoveMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MoveMessage.class, Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object playerId_ = "";
    /**
     * <code>string playerId = 1;</code>
     * @return The playerId.
     */
    @Override
    public String getPlayerId() {
      Object ref = playerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <code>string playerId = 1;</code>
     * @return The bytes for playerId.
     */
    @Override
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      Object ref = playerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSX_FIELD_NUMBER = 2;
    private float posX_ = 0F;
    /**
     * <code>float posX = 2;</code>
     * @return The posX.
     */
    @Override
    public float getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 3;
    private float posY_ = 0F;
    /**
     * <code>float posY = 3;</code>
     * @return The posY.
     */
    @Override
    public float getPosY() {
      return posY_;
    }

    public static final int POSZ_FIELD_NUMBER = 4;
    private float posZ_ = 0F;
    /**
     * <code>float posZ = 4;</code>
     * @return The posZ.
     */
    @Override
    public float getPosZ() {
      return posZ_;
    }

    public static final int ROTX_FIELD_NUMBER = 5;
    private float rotX_ = 0F;
    /**
     * <code>float rotX = 5;</code>
     * @return The rotX.
     */
    @Override
    public float getRotX() {
      return rotX_;
    }

    public static final int ROTY_FIELD_NUMBER = 6;
    private float rotY_ = 0F;
    /**
     * <code>float rotY = 6;</code>
     * @return The rotY.
     */
    @Override
    public float getRotY() {
      return rotY_;
    }

    public static final int ROTZ_FIELD_NUMBER = 7;
    private float rotZ_ = 0F;
    /**
     * <code>float rotZ = 7;</code>
     * @return The rotZ.
     */
    @Override
    public float getRotZ() {
      return rotZ_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, playerId_);
      }
      if (Float.floatToRawIntBits(posX_) != 0) {
        output.writeFloat(2, posX_);
      }
      if (Float.floatToRawIntBits(posY_) != 0) {
        output.writeFloat(3, posY_);
      }
      if (Float.floatToRawIntBits(posZ_) != 0) {
        output.writeFloat(4, posZ_);
      }
      if (Float.floatToRawIntBits(rotX_) != 0) {
        output.writeFloat(5, rotX_);
      }
      if (Float.floatToRawIntBits(rotY_) != 0) {
        output.writeFloat(6, rotY_);
      }
      if (Float.floatToRawIntBits(rotZ_) != 0) {
        output.writeFloat(7, rotZ_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerId_);
      }
      if (Float.floatToRawIntBits(posX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, posX_);
      }
      if (Float.floatToRawIntBits(posY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, posY_);
      }
      if (Float.floatToRawIntBits(posZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, posZ_);
      }
      if (Float.floatToRawIntBits(rotX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, rotX_);
      }
      if (Float.floatToRawIntBits(rotY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, rotY_);
      }
      if (Float.floatToRawIntBits(rotZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, rotZ_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MoveMessage)) {
        return super.equals(obj);
      }
      MoveMessage other = (MoveMessage) obj;

      if (!getPlayerId()
          .equals(other.getPlayerId())) return false;
      if (Float.floatToIntBits(getPosX())
          != Float.floatToIntBits(
              other.getPosX())) return false;
      if (Float.floatToIntBits(getPosY())
          != Float.floatToIntBits(
              other.getPosY())) return false;
      if (Float.floatToIntBits(getPosZ())
          != Float.floatToIntBits(
              other.getPosZ())) return false;
      if (Float.floatToIntBits(getRotX())
          != Float.floatToIntBits(
              other.getRotX())) return false;
      if (Float.floatToIntBits(getRotY())
          != Float.floatToIntBits(
              other.getRotY())) return false;
      if (Float.floatToIntBits(getRotZ())
          != Float.floatToIntBits(
              other.getRotZ())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      hash = (37 * hash) + POSX_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPosX());
      hash = (37 * hash) + POSY_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPosY());
      hash = (37 * hash) + POSZ_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPosZ());
      hash = (37 * hash) + ROTX_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRotX());
      hash = (37 * hash) + ROTY_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRotY());
      hash = (37 * hash) + ROTZ_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRotZ());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MoveMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MoveMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MoveMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MoveMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MoveMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MoveMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MoveMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MoveMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MoveMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MoveMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MoveMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MoveMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MoveMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sirius.bootstrap.msg.MoveMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sirius.bootstrap.msg.MoveMessage)
        MoveMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_com_sirius_bootstrap_msg_MoveMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_com_sirius_bootstrap_msg_MoveMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MoveMessage.class, Builder.class);
      }

      // Construct using com.sirius.bootstrap.msg.Msg.MoveMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerId_ = "";
        posX_ = 0F;
        posY_ = 0F;
        posZ_ = 0F;
        rotX_ = 0F;
        rotY_ = 0F;
        rotZ_ = 0F;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_com_sirius_bootstrap_msg_MoveMessage_descriptor;
      }

      @Override
      public MoveMessage getDefaultInstanceForType() {
        return MoveMessage.getDefaultInstance();
      }

      @Override
      public MoveMessage build() {
        MoveMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MoveMessage buildPartial() {
        MoveMessage result = new MoveMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MoveMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerId_ = playerId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.posX_ = posX_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.posY_ = posY_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.posZ_ = posZ_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rotX_ = rotX_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.rotY_ = rotY_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.rotZ_ = rotZ_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MoveMessage) {
          return mergeFrom((MoveMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MoveMessage other) {
        if (other == MoveMessage.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (Float.floatToRawIntBits(other.getPosX()) != 0) {
          setPosX(other.getPosX());
        }
        if (Float.floatToRawIntBits(other.getPosY()) != 0) {
          setPosY(other.getPosY());
        }
        if (Float.floatToRawIntBits(other.getPosZ()) != 0) {
          setPosZ(other.getPosZ());
        }
        if (Float.floatToRawIntBits(other.getRotX()) != 0) {
          setRotX(other.getRotX());
        }
        if (Float.floatToRawIntBits(other.getRotY()) != 0) {
          setRotY(other.getRotY());
        }
        if (Float.floatToRawIntBits(other.getRotZ()) != 0) {
          setRotZ(other.getRotZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                playerId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 21: {
                posX_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                posY_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 37: {
                posZ_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 45: {
                rotX_ = input.readFloat();
                bitField0_ |= 0x00000010;
                break;
              } // case 45
              case 53: {
                rotY_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              case 61: {
                rotZ_ = input.readFloat();
                bitField0_ |= 0x00000040;
                break;
              } // case 61
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object playerId_ = "";
      /**
       * <code>string playerId = 1;</code>
       * @return The playerId.
       */
      public String getPlayerId() {
        Object ref = playerId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       * @return The bytes for playerId.
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        playerId_ = getDefaultInstance().getPlayerId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       * @param value The bytes for playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private float posX_ ;
      /**
       * <code>float posX = 2;</code>
       * @return The posX.
       */
      @Override
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>float posX = 2;</code>
       * @param value The posX to set.
       * @return This builder for chaining.
       */
      public Builder setPosX(float value) {

        posX_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float posX = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>float posY = 3;</code>
       * @return The posY.
       */
      @Override
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>float posY = 3;</code>
       * @param value The posY to set.
       * @return This builder for chaining.
       */
      public Builder setPosY(float value) {

        posY_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float posY = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        posY_ = 0F;
        onChanged();
        return this;
      }

      private float posZ_ ;
      /**
       * <code>float posZ = 4;</code>
       * @return The posZ.
       */
      @Override
      public float getPosZ() {
        return posZ_;
      }
      /**
       * <code>float posZ = 4;</code>
       * @param value The posZ to set.
       * @return This builder for chaining.
       */
      public Builder setPosZ(float value) {

        posZ_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float posZ = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        posZ_ = 0F;
        onChanged();
        return this;
      }

      private float rotX_ ;
      /**
       * <code>float rotX = 5;</code>
       * @return The rotX.
       */
      @Override
      public float getRotX() {
        return rotX_;
      }
      /**
       * <code>float rotX = 5;</code>
       * @param value The rotX to set.
       * @return This builder for chaining.
       */
      public Builder setRotX(float value) {

        rotX_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>float rotX = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRotX() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rotX_ = 0F;
        onChanged();
        return this;
      }

      private float rotY_ ;
      /**
       * <code>float rotY = 6;</code>
       * @return The rotY.
       */
      @Override
      public float getRotY() {
        return rotY_;
      }
      /**
       * <code>float rotY = 6;</code>
       * @param value The rotY to set.
       * @return This builder for chaining.
       */
      public Builder setRotY(float value) {

        rotY_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>float rotY = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRotY() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rotY_ = 0F;
        onChanged();
        return this;
      }

      private float rotZ_ ;
      /**
       * <code>float rotZ = 7;</code>
       * @return The rotZ.
       */
      @Override
      public float getRotZ() {
        return rotZ_;
      }
      /**
       * <code>float rotZ = 7;</code>
       * @param value The rotZ to set.
       * @return This builder for chaining.
       */
      public Builder setRotZ(float value) {

        rotZ_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>float rotZ = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRotZ() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rotZ_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sirius.bootstrap.msg.MoveMessage)
    }

    // @@protoc_insertion_point(class_scope:com.sirius.bootstrap.msg.MoveMessage)
    private static final MoveMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MoveMessage();
    }

    public static MoveMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoveMessage>
        PARSER = new com.google.protobuf.AbstractParser<MoveMessage>() {
      @Override
      public MoveMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MoveMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MoveMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public MoveMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sirius.bootstrap.msg.PlayerState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string player_id = 1;</code>
     * @return The playerId.
     */
    String getPlayerId();
    /**
     * <code>string player_id = 1;</code>
     * @return The bytes for playerId.
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    /**
     * <code>float position_x = 2;</code>
     * @return The positionX.
     */
    float getPositionX();

    /**
     * <code>float position_y = 3;</code>
     * @return The positionY.
     */
    float getPositionY();

    /**
     * <code>float position_z = 4;</code>
     * @return The positionZ.
     */
    float getPositionZ();

    /**
     * <code>float rotation_y = 5;</code>
     * @return The rotationY.
     */
    float getRotationY();

    /**
     * <code>float speed = 6;</code>
     * @return The speed.
     */
    float getSpeed();

    /**
     * <code>bool is_jumping = 7;</code>
     * @return The isJumping.
     */
    boolean getIsJumping();

    /**
     * <code>bool is_sprinting = 8;</code>
     * @return The isSprinting.
     */
    boolean getIsSprinting();

    /**
     * <code>double timestamp = 9;</code>
     * @return The timestamp.
     */
    double getTimestamp();
  }
  /**
   * Protobuf type {@code com.sirius.bootstrap.msg.PlayerState}
   */
  public static final class PlayerState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.sirius.bootstrap.msg.PlayerState)
      PlayerStateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        PlayerState.class.getName());
    }
    // Use PlayerState.newBuilder() to construct.
    private PlayerState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlayerState() {
      playerId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_com_sirius_bootstrap_msg_PlayerState_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_com_sirius_bootstrap_msg_PlayerState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlayerState.class, Builder.class);
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object playerId_ = "";
    /**
     * <code>string player_id = 1;</code>
     * @return The playerId.
     */
    @Override
    public String getPlayerId() {
      Object ref = playerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <code>string player_id = 1;</code>
     * @return The bytes for playerId.
     */
    @Override
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      Object ref = playerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_X_FIELD_NUMBER = 2;
    private float positionX_ = 0F;
    /**
     * <code>float position_x = 2;</code>
     * @return The positionX.
     */
    @Override
    public float getPositionX() {
      return positionX_;
    }

    public static final int POSITION_Y_FIELD_NUMBER = 3;
    private float positionY_ = 0F;
    /**
     * <code>float position_y = 3;</code>
     * @return The positionY.
     */
    @Override
    public float getPositionY() {
      return positionY_;
    }

    public static final int POSITION_Z_FIELD_NUMBER = 4;
    private float positionZ_ = 0F;
    /**
     * <code>float position_z = 4;</code>
     * @return The positionZ.
     */
    @Override
    public float getPositionZ() {
      return positionZ_;
    }

    public static final int ROTATION_Y_FIELD_NUMBER = 5;
    private float rotationY_ = 0F;
    /**
     * <code>float rotation_y = 5;</code>
     * @return The rotationY.
     */
    @Override
    public float getRotationY() {
      return rotationY_;
    }

    public static final int SPEED_FIELD_NUMBER = 6;
    private float speed_ = 0F;
    /**
     * <code>float speed = 6;</code>
     * @return The speed.
     */
    @Override
    public float getSpeed() {
      return speed_;
    }

    public static final int IS_JUMPING_FIELD_NUMBER = 7;
    private boolean isJumping_ = false;
    /**
     * <code>bool is_jumping = 7;</code>
     * @return The isJumping.
     */
    @Override
    public boolean getIsJumping() {
      return isJumping_;
    }

    public static final int IS_SPRINTING_FIELD_NUMBER = 8;
    private boolean isSprinting_ = false;
    /**
     * <code>bool is_sprinting = 8;</code>
     * @return The isSprinting.
     */
    @Override
    public boolean getIsSprinting() {
      return isSprinting_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private double timestamp_ = 0D;
    /**
     * <code>double timestamp = 9;</code>
     * @return The timestamp.
     */
    @Override
    public double getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, playerId_);
      }
      if (Float.floatToRawIntBits(positionX_) != 0) {
        output.writeFloat(2, positionX_);
      }
      if (Float.floatToRawIntBits(positionY_) != 0) {
        output.writeFloat(3, positionY_);
      }
      if (Float.floatToRawIntBits(positionZ_) != 0) {
        output.writeFloat(4, positionZ_);
      }
      if (Float.floatToRawIntBits(rotationY_) != 0) {
        output.writeFloat(5, rotationY_);
      }
      if (Float.floatToRawIntBits(speed_) != 0) {
        output.writeFloat(6, speed_);
      }
      if (isJumping_ != false) {
        output.writeBool(7, isJumping_);
      }
      if (isSprinting_ != false) {
        output.writeBool(8, isSprinting_);
      }
      if (Double.doubleToRawLongBits(timestamp_) != 0) {
        output.writeDouble(9, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerId_);
      }
      if (Float.floatToRawIntBits(positionX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, positionX_);
      }
      if (Float.floatToRawIntBits(positionY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, positionY_);
      }
      if (Float.floatToRawIntBits(positionZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, positionZ_);
      }
      if (Float.floatToRawIntBits(rotationY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, rotationY_);
      }
      if (Float.floatToRawIntBits(speed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, speed_);
      }
      if (isJumping_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isJumping_);
      }
      if (isSprinting_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isSprinting_);
      }
      if (Double.doubleToRawLongBits(timestamp_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlayerState)) {
        return super.equals(obj);
      }
      PlayerState other = (PlayerState) obj;

      if (!getPlayerId()
          .equals(other.getPlayerId())) return false;
      if (Float.floatToIntBits(getPositionX())
          != Float.floatToIntBits(
              other.getPositionX())) return false;
      if (Float.floatToIntBits(getPositionY())
          != Float.floatToIntBits(
              other.getPositionY())) return false;
      if (Float.floatToIntBits(getPositionZ())
          != Float.floatToIntBits(
              other.getPositionZ())) return false;
      if (Float.floatToIntBits(getRotationY())
          != Float.floatToIntBits(
              other.getRotationY())) return false;
      if (Float.floatToIntBits(getSpeed())
          != Float.floatToIntBits(
              other.getSpeed())) return false;
      if (getIsJumping()
          != other.getIsJumping()) return false;
      if (getIsSprinting()
          != other.getIsSprinting()) return false;
      if (Double.doubleToLongBits(getTimestamp())
          != Double.doubleToLongBits(
              other.getTimestamp())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      hash = (37 * hash) + POSITION_X_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPositionX());
      hash = (37 * hash) + POSITION_Y_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPositionY());
      hash = (37 * hash) + POSITION_Z_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPositionZ());
      hash = (37 * hash) + ROTATION_Y_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRotationY());
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getSpeed());
      hash = (37 * hash) + IS_JUMPING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsJumping());
      hash = (37 * hash) + IS_SPRINTING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSprinting());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getTimestamp()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlayerState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static PlayerState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PlayerState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PlayerState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static PlayerState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlayerState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sirius.bootstrap.msg.PlayerState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sirius.bootstrap.msg.PlayerState)
        PlayerStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_com_sirius_bootstrap_msg_PlayerState_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_com_sirius_bootstrap_msg_PlayerState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlayerState.class, Builder.class);
      }

      // Construct using com.sirius.bootstrap.msg.Msg.PlayerState.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerId_ = "";
        positionX_ = 0F;
        positionY_ = 0F;
        positionZ_ = 0F;
        rotationY_ = 0F;
        speed_ = 0F;
        isJumping_ = false;
        isSprinting_ = false;
        timestamp_ = 0D;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_com_sirius_bootstrap_msg_PlayerState_descriptor;
      }

      @Override
      public PlayerState getDefaultInstanceForType() {
        return PlayerState.getDefaultInstance();
      }

      @Override
      public PlayerState build() {
        PlayerState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PlayerState buildPartial() {
        PlayerState result = new PlayerState(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PlayerState result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerId_ = playerId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.positionX_ = positionX_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.positionY_ = positionY_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.positionZ_ = positionZ_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rotationY_ = rotationY_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.speed_ = speed_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.isJumping_ = isJumping_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.isSprinting_ = isSprinting_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlayerState) {
          return mergeFrom((PlayerState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlayerState other) {
        if (other == PlayerState.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (Float.floatToRawIntBits(other.getPositionX()) != 0) {
          setPositionX(other.getPositionX());
        }
        if (Float.floatToRawIntBits(other.getPositionY()) != 0) {
          setPositionY(other.getPositionY());
        }
        if (Float.floatToRawIntBits(other.getPositionZ()) != 0) {
          setPositionZ(other.getPositionZ());
        }
        if (Float.floatToRawIntBits(other.getRotationY()) != 0) {
          setRotationY(other.getRotationY());
        }
        if (Float.floatToRawIntBits(other.getSpeed()) != 0) {
          setSpeed(other.getSpeed());
        }
        if (other.getIsJumping() != false) {
          setIsJumping(other.getIsJumping());
        }
        if (other.getIsSprinting() != false) {
          setIsSprinting(other.getIsSprinting());
        }
        if (Double.doubleToRawLongBits(other.getTimestamp()) != 0) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                playerId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 21: {
                positionX_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                positionY_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 37: {
                positionZ_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 45: {
                rotationY_ = input.readFloat();
                bitField0_ |= 0x00000010;
                break;
              } // case 45
              case 53: {
                speed_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              case 56: {
                isJumping_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                isSprinting_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 73: {
                timestamp_ = input.readDouble();
                bitField0_ |= 0x00000100;
                break;
              } // case 73
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object playerId_ = "";
      /**
       * <code>string player_id = 1;</code>
       * @return The playerId.
       */
      public String getPlayerId() {
        Object ref = playerId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string player_id = 1;</code>
       * @return The bytes for playerId.
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player_id = 1;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string player_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        playerId_ = getDefaultInstance().getPlayerId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string player_id = 1;</code>
       * @param value The bytes for playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private float positionX_ ;
      /**
       * <code>float position_x = 2;</code>
       * @return The positionX.
       */
      @Override
      public float getPositionX() {
        return positionX_;
      }
      /**
       * <code>float position_x = 2;</code>
       * @param value The positionX to set.
       * @return This builder for chaining.
       */
      public Builder setPositionX(float value) {

        positionX_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float position_x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPositionX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        positionX_ = 0F;
        onChanged();
        return this;
      }

      private float positionY_ ;
      /**
       * <code>float position_y = 3;</code>
       * @return The positionY.
       */
      @Override
      public float getPositionY() {
        return positionY_;
      }
      /**
       * <code>float position_y = 3;</code>
       * @param value The positionY to set.
       * @return This builder for chaining.
       */
      public Builder setPositionY(float value) {

        positionY_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float position_y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPositionY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        positionY_ = 0F;
        onChanged();
        return this;
      }

      private float positionZ_ ;
      /**
       * <code>float position_z = 4;</code>
       * @return The positionZ.
       */
      @Override
      public float getPositionZ() {
        return positionZ_;
      }
      /**
       * <code>float position_z = 4;</code>
       * @param value The positionZ to set.
       * @return This builder for chaining.
       */
      public Builder setPositionZ(float value) {

        positionZ_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float position_z = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPositionZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        positionZ_ = 0F;
        onChanged();
        return this;
      }

      private float rotationY_ ;
      /**
       * <code>float rotation_y = 5;</code>
       * @return The rotationY.
       */
      @Override
      public float getRotationY() {
        return rotationY_;
      }
      /**
       * <code>float rotation_y = 5;</code>
       * @param value The rotationY to set.
       * @return This builder for chaining.
       */
      public Builder setRotationY(float value) {

        rotationY_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>float rotation_y = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRotationY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rotationY_ = 0F;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <code>float speed = 6;</code>
       * @return The speed.
       */
      @Override
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>float speed = 6;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(float value) {

        speed_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>float speed = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000020);
        speed_ = 0F;
        onChanged();
        return this;
      }

      private boolean isJumping_ ;
      /**
       * <code>bool is_jumping = 7;</code>
       * @return The isJumping.
       */
      @Override
      public boolean getIsJumping() {
        return isJumping_;
      }
      /**
       * <code>bool is_jumping = 7;</code>
       * @param value The isJumping to set.
       * @return This builder for chaining.
       */
      public Builder setIsJumping(boolean value) {

        isJumping_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_jumping = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsJumping() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isJumping_ = false;
        onChanged();
        return this;
      }

      private boolean isSprinting_ ;
      /**
       * <code>bool is_sprinting = 8;</code>
       * @return The isSprinting.
       */
      @Override
      public boolean getIsSprinting() {
        return isSprinting_;
      }
      /**
       * <code>bool is_sprinting = 8;</code>
       * @param value The isSprinting to set.
       * @return This builder for chaining.
       */
      public Builder setIsSprinting(boolean value) {

        isSprinting_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_sprinting = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSprinting() {
        bitField0_ = (bitField0_ & ~0x00000080);
        isSprinting_ = false;
        onChanged();
        return this;
      }

      private double timestamp_ ;
      /**
       * <code>double timestamp = 9;</code>
       * @return The timestamp.
       */
      @Override
      public double getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>double timestamp = 9;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(double value) {

        timestamp_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>double timestamp = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        timestamp_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sirius.bootstrap.msg.PlayerState)
    }

    // @@protoc_insertion_point(class_scope:com.sirius.bootstrap.msg.PlayerState)
    private static final PlayerState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlayerState();
    }

    public static PlayerState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerState>
        PARSER = new com.google.protobuf.AbstractParser<PlayerState>() {
      @Override
      public PlayerState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerState> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PlayerState> getParserForType() {
      return PARSER;
    }

    @Override
    public PlayerState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_bootstrap_msg_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sirius_bootstrap_msg_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_bootstrap_msg_MoveMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sirius_bootstrap_msg_MoveMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_bootstrap_msg_PlayerState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sirius_bootstrap_msg_PlayerState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tmsg.proto\022\030com.sirius.bootstrap.msg\"Q\n" +
      "\007Message\022=\n\013moveMessage\030\351\007 \001(\0132%.com.sir" +
      "ius.bootstrap.msg.MoveMessageH\000B\007\n\005msgId" +
      "\"s\n\013MoveMessage\022\020\n\010playerId\030\001 \001(\t\022\014\n\004pos" +
      "X\030\002 \001(\002\022\014\n\004posY\030\003 \001(\002\022\014\n\004posZ\030\004 \001(\002\022\014\n\004r" +
      "otX\030\005 \001(\002\022\014\n\004rotY\030\006 \001(\002\022\014\n\004rotZ\030\007 \001(\002\"\274\001" +
      "\n\013PlayerState\022\021\n\tplayer_id\030\001 \001(\t\022\022\n\nposi" +
      "tion_x\030\002 \001(\002\022\022\n\nposition_y\030\003 \001(\002\022\022\n\nposi" +
      "tion_z\030\004 \001(\002\022\022\n\nrotation_y\030\005 \001(\002\022\r\n\005spee" +
      "d\030\006 \001(\002\022\022\n\nis_jumping\030\007 \001(\010\022\024\n\014is_sprint" +
      "ing\030\010 \001(\010\022\021\n\ttimestamp\030\t \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sirius_bootstrap_msg_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sirius_bootstrap_msg_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sirius_bootstrap_msg_Message_descriptor,
        new String[] { "MoveMessage", "MsgId", });
    internal_static_com_sirius_bootstrap_msg_MoveMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sirius_bootstrap_msg_MoveMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sirius_bootstrap_msg_MoveMessage_descriptor,
        new String[] { "PlayerId", "PosX", "PosY", "PosZ", "RotX", "RotY", "RotZ", });
    internal_static_com_sirius_bootstrap_msg_PlayerState_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sirius_bootstrap_msg_PlayerState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sirius_bootstrap_msg_PlayerState_descriptor,
        new String[] { "PlayerId", "PositionX", "PositionY", "PositionZ", "RotationY", "Speed", "IsJumping", "IsSprinting", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
